import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import {
  Sparkles,
  FileText,
  CheckCircle2,
  AlertTriangle,
  Lightbulb,
  Compass,
  Award,
} from "lucide-react";

export const Route = createFileRoute("/reports/$slug")({
  head: () => ({
    meta: [
      { title: "Shared ATS Report — Hireway" },
      { name: "description", content: "View a candidate's ATS compatibility score and skill analysis, shared via Hireway." },
      { property: "og:title", content: "Shared ATS Report — Hireway" },
      { property: "og:description", content: "View a candidate's ATS compatibility score and skill analysis, shared via Hireway." },
      { property: "og:type", content: "profile" },
      { name: "twitter:title", content: "Shared ATS Report — Hireway" },
      { name: "twitter:description", content: "View a candidate's ATS compatibility score and skill analysis, shared via Hireway." },
      { name: "twitter:card", content: "summary" },
    ],
  }),
  component: PublicReportPage,
});

function PublicReportPage() {
  const { slug } = Route.useParams();

  // Uses the SECURITY DEFINER RPC so anon callers can read the curated
  // analysis fields without any direct access to resume_versions (which
  // would expose parsed_text and other PII).
  // Returns 0 rows when the slug is invalid, expired, or revoked.
  const reportQuery = useQuery({
    queryKey: ["public-report", slug],
    retry: false,
    queryFn: async () => {
      const { data, error } = await supabase
        .rpc("get_public_report", { p_slug: slug })
        .single();
      if (error) throw error;
      if (!data) throw new Error("Report not found or has expired.");
      return data as {
        display_name: string | null;
        ats_score: number | null;
        readiness_score: number | null;
        summary: string | null;
        detected_skills: string[];
        missing_keywords: string[];
        skill_gaps: string[];
        suggestions: unknown;
      };
    },
  });

  if (reportQuery.isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background text-foreground">
        <div className="text-center space-y-4">
          <FileText className="h-12 w-12 text-primary animate-pulse mx-auto" />
          <p className="text-sm text-muted-foreground">Loading public ATS report…</p>
        </div>
      </div>
    );
  }

  if (reportQuery.isError) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background text-foreground p-6">
        <Card className="max-w-md w-full text-center p-8 border border-red-500/20 bg-red-500/5">
          <AlertTriangle className="h-12 w-12 text-destructive mx-auto mb-4" />
          <h3 className="font-bold text-lg text-destructive">Report Not Found</h3>
          <p className="text-sm text-muted-foreground mt-2">
            This link may have expired, been revoked, or is invalid.
          </p>
        </Card>
      </div>
    );
  }

  const version = reportQuery.data;
  const suggestions: string[] = Array.isArray(version?.suggestions)
    ? (version!.suggestions as string[])
    : [];

  return (
    <div className="min-h-screen bg-background text-foreground py-12 px-6">
      <div className="max-w-4xl mx-auto space-y-8 animate-fade-in">
        {/* Header */}
        <div className="text-center space-y-3">
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full border border-primary/20 bg-primary/5 text-primary text-xs font-semibold">
            <Sparkles className="h-3.5 w-3.5" /> Public ATS Optimization Report
          </div>
          <h1 className="text-4xl font-extrabold tracking-tight bg-gradient-to-r from-primary via-purple-500 to-indigo-600 bg-clip-text text-transparent">
            {version?.display_name || "Candidate Profile"}
          </h1>
          <p className="text-sm text-muted-foreground">
            Verified ATS compatibility analysis generated by JobVerse AI.
          </p>
        </div>

        {/* Scores */}
        <div className="grid gap-6 md:grid-cols-2">
          <Card className="bg-card border border-muted/50 shadow-md p-6 flex flex-col justify-between">
            <div className="space-y-3">
              <div className="flex justify-between items-center">
                <span className="font-semibold text-sm flex items-center gap-1.5">
                  <CheckCircle2 className="h-4 w-4 text-green-500" /> ATS Compatibility Score
                </span>
                <span className="font-bold text-green-500 text-xl">{version?.ats_score ?? 0}%</span>
              </div>
              <Progress value={version?.ats_score ?? 0} className="h-3 bg-muted/30" />
            </div>
            <p className="text-xs text-muted-foreground mt-4 leading-relaxed">
              Based on keyword matches, formatting constraints, and industry-standard parser tests.
            </p>
          </Card>

          <Card className="bg-card border border-muted/50 shadow-md p-6 flex flex-col justify-between">
            <div className="space-y-3">
              <div className="flex justify-between items-center">
                <span className="font-semibold text-sm flex items-center gap-1.5">
                  <Award className="h-4 w-4 text-primary" /> Interview Readiness Score
                </span>
                <span className="font-bold text-primary text-xl">
                  {version?.readiness_score ?? 0}%
                </span>
              </div>
              <Progress value={version?.readiness_score ?? 0} className="h-3 bg-muted/30" />
            </div>
            <p className="text-xs text-muted-foreground mt-4 leading-relaxed">
              Reflects depth of experience, impact metrics, and project descriptions.
            </p>
          </Card>
        </div>

        {/* Executive Summary */}
        {version?.summary && (
          <Card className="bg-card border border-muted/50 shadow-md p-6">
            <CardHeader className="px-0 pt-0">
              <CardTitle className="text-lg flex items-center gap-2">
                <Compass className="h-5 w-5 text-primary" /> Executive Summary
              </CardTitle>
            </CardHeader>
            <CardContent className="px-0 pb-0 text-sm leading-relaxed text-muted-foreground">
              {version.summary}
            </CardContent>
          </Card>
        )}

        {/* Skills */}
        <div className="grid gap-6 md:grid-cols-2">
          <Card className="bg-card border border-muted/50 shadow-md p-6">
            <h3 className="font-bold text-sm mb-4 text-foreground/90">Detected Capabilities</h3>
            <div className="flex flex-wrap gap-1.5">
              {(version?.detected_skills?.length ?? 0) > 0 ? (
                version!.detected_skills.map((skill) => (
                  <Badge
                    key={skill}
                    variant="secondary"
                    className="text-xs bg-primary/5 text-primary border border-primary/10"
                  >
                    {skill}
                  </Badge>
                ))
              ) : (
                <span className="text-xs text-muted-foreground">No capabilities parsed.</span>
              )}
            </div>
          </Card>

          <Card className="bg-card border border-muted/50 shadow-md p-6">
            <h3 className="font-bold text-sm mb-4 text-foreground/90 flex items-center gap-1.5">
              <AlertTriangle className="h-4 w-4 text-amber-500" /> Missing Core Keywords
            </h3>
            <div className="flex flex-wrap gap-1.5">
              {(version?.missing_keywords?.length ?? 0) > 0 ? (
                version!.missing_keywords.map((kw) => (
                  <Badge
                    key={kw}
                    variant="outline"
                    className="text-xs border-amber-500/30 text-amber-500 bg-amber-500/5"
                  >
                    {kw}
                  </Badge>
                ))
              ) : (
                <span className="text-xs text-muted-foreground">
                  No missing keywords identified.
                </span>
              )}
            </div>
          </Card>
        </div>

        {/* Suggestions */}
        {suggestions.length > 0 && (
          <Card className="bg-card border border-muted/50 shadow-md p-6">
            <CardHeader className="px-0 pt-0">
              <CardTitle className="text-lg flex items-center gap-2">
                <Lightbulb className="h-5 w-5 text-amber-500" /> Actionable Recommendations
              </CardTitle>
            </CardHeader>
            <CardContent className="px-0 pb-0">
              <ul className="space-y-3">
                {suggestions.map((suggestion, idx) => (
                  <li key={idx} className="text-sm flex gap-3 text-muted-foreground leading-relaxed">
                    <span className="text-primary font-bold shrink-0">{idx + 1}.</span>
                    <span>{suggestion}</span>
                  </li>
                ))}
              </ul>
            </CardContent>
          </Card>
        )}

        <p className="text-center text-xs text-muted-foreground pb-4">
          This report was shared by the candidate and contains only their analysis scores — not their
          resume text.
        </p>
      </div>
    </div>
  );
}
