/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as ReportsSlugRouteImport } from './routes/reports.$slug'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'
import { Route as CompaniesCompanyIdRouteImport } from './routes/companies.$companyId'
import { Route as AuthVerifiedRouteImport } from './routes/auth.verified'
import { Route as AuthCheckEmailRouteImport } from './routes/auth.check-email'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEmployerIndexRouteImport } from './routes/_authenticated/employer.index'
import { Route as AuthenticatedSeekerTrackerRouteImport } from './routes/_authenticated/seeker.tracker'
import { Route as AuthenticatedSeekerSettingsRouteImport } from './routes/_authenticated/seeker.settings'
import { Route as AuthenticatedSeekerSavedJobsRouteImport } from './routes/_authenticated/seeker.saved-jobs'
import { Route as AuthenticatedSeekerResumeAnalyzerRouteImport } from './routes/_authenticated/seeker.resume-analyzer'
import { Route as AuthenticatedSeekerReportsRouteImport } from './routes/_authenticated/seeker.reports'
import { Route as AuthenticatedSeekerProfileRouteImport } from './routes/_authenticated/seeker.profile'
import { Route as AuthenticatedSeekerJobMatchesRouteImport } from './routes/_authenticated/seeker.job-matches'
import { Route as AuthenticatedSeekerCoachRouteImport } from './routes/_authenticated/seeker.coach'
import { Route as AuthenticatedSeekerApplicationsRouteImport } from './routes/_authenticated/seeker.applications'
import { Route as AuthenticatedEmployerDashboardRouteImport } from './routes/_authenticated/employer.dashboard'
import { Route as AuthenticatedEmployerCompanyRouteImport } from './routes/_authenticated/employer.company'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminJobsRouteImport } from './routes/_authenticated/admin.jobs'
import { Route as AuthenticatedAdminEmployersRouteImport } from './routes/_authenticated/admin.employers'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedEmployerJobsIndexRouteImport } from './routes/_authenticated/employer.jobs.index'
import { Route as AuthenticatedEmployerJobsNewRouteImport } from './routes/_authenticated/employer.jobs.new'
import { Route as AuthenticatedEmployerJobsIdEditRouteImport } from './routes/_authenticated/employer.jobs.$id.edit'
import { Route as AuthenticatedEmployerJobsIdApplicantsRouteImport } from './routes/_authenticated/employer.jobs.$id.applicants'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsSlugRoute = ReportsSlugRouteImport.update({
  id: '/reports/$slug',
  path: '/reports/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesCompanyIdRoute = CompaniesCompanyIdRouteImport.update({
  id: '/companies/$companyId',
  path: '/companies/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifiedRoute = AuthVerifiedRouteImport.update({
  id: '/verified',
  path: '/verified',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCheckEmailRoute = AuthCheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployerIndexRoute =
  AuthenticatedEmployerIndexRouteImport.update({
    id: '/employer/',
    path: '/employer/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSeekerTrackerRoute =
  AuthenticatedSeekerTrackerRouteImport.update({
    id: '/seeker/tracker',
    path: '/seeker/tracker',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSeekerSettingsRoute =
  AuthenticatedSeekerSettingsRouteImport.update({
    id: '/seeker/settings',
    path: '/seeker/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSeekerSavedJobsRoute =
  AuthenticatedSeekerSavedJobsRouteImport.update({
    id: '/seeker/saved-jobs',
    path: '/seeker/saved-jobs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSeekerResumeAnalyzerRoute =
  AuthenticatedSeekerResumeAnalyzerRouteImport.update({
    id: '/seeker/resume-analyzer',
    path: '/seeker/resume-analyzer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSeekerReportsRoute =
  AuthenticatedSeekerReportsRouteImport.update({
    id: '/seeker/reports',
    path: '/seeker/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSeekerProfileRoute =
  AuthenticatedSeekerProfileRouteImport.update({
    id: '/seeker/profile',
    path: '/seeker/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSeekerJobMatchesRoute =
  AuthenticatedSeekerJobMatchesRouteImport.update({
    id: '/seeker/job-matches',
    path: '/seeker/job-matches',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSeekerCoachRoute =
  AuthenticatedSeekerCoachRouteImport.update({
    id: '/seeker/coach',
    path: '/seeker/coach',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSeekerApplicationsRoute =
  AuthenticatedSeekerApplicationsRouteImport.update({
    id: '/seeker/applications',
    path: '/seeker/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerDashboardRoute =
  AuthenticatedEmployerDashboardRouteImport.update({
    id: '/employer/dashboard',
    path: '/employer/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerCompanyRoute =
  AuthenticatedEmployerCompanyRouteImport.update({
    id: '/employer/company',
    path: '/employer/company',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminJobsRoute = AuthenticatedAdminJobsRouteImport.update({
  id: '/admin/jobs',
  path: '/admin/jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminEmployersRoute =
  AuthenticatedAdminEmployersRouteImport.update({
    id: '/admin/employers',
    path: '/admin/employers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/admin/categories',
    path: '/admin/categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerJobsIndexRoute =
  AuthenticatedEmployerJobsIndexRouteImport.update({
    id: '/employer/jobs/',
    path: '/employer/jobs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerJobsNewRoute =
  AuthenticatedEmployerJobsNewRouteImport.update({
    id: '/employer/jobs/new',
    path: '/employer/jobs/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerJobsIdEditRoute =
  AuthenticatedEmployerJobsIdEditRouteImport.update({
    id: '/employer/jobs/$id/edit',
    path: '/employer/jobs/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerJobsIdApplicantsRoute =
  AuthenticatedEmployerJobsIdApplicantsRouteImport.update({
    id: '/employer/jobs/$id/applicants',
    path: '/employer/jobs/$id/applicants',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/jobs/$id': typeof JobsIdRoute
  '/reports/$slug': typeof ReportsSlugRoute
  '/companies/': typeof CompaniesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/employers': typeof AuthenticatedAdminEmployersRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/employer/company': typeof AuthenticatedEmployerCompanyRoute
  '/employer/dashboard': typeof AuthenticatedEmployerDashboardRoute
  '/seeker/applications': typeof AuthenticatedSeekerApplicationsRoute
  '/seeker/coach': typeof AuthenticatedSeekerCoachRoute
  '/seeker/job-matches': typeof AuthenticatedSeekerJobMatchesRoute
  '/seeker/profile': typeof AuthenticatedSeekerProfileRoute
  '/seeker/reports': typeof AuthenticatedSeekerReportsRoute
  '/seeker/resume-analyzer': typeof AuthenticatedSeekerResumeAnalyzerRoute
  '/seeker/saved-jobs': typeof AuthenticatedSeekerSavedJobsRoute
  '/seeker/settings': typeof AuthenticatedSeekerSettingsRoute
  '/seeker/tracker': typeof AuthenticatedSeekerTrackerRoute
  '/employer/': typeof AuthenticatedEmployerIndexRoute
  '/employer/jobs/new': typeof AuthenticatedEmployerJobsNewRoute
  '/employer/jobs/': typeof AuthenticatedEmployerJobsIndexRoute
  '/employer/jobs/$id/applicants': typeof AuthenticatedEmployerJobsIdApplicantsRoute
  '/employer/jobs/$id/edit': typeof AuthenticatedEmployerJobsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/jobs/$id': typeof JobsIdRoute
  '/reports/$slug': typeof ReportsSlugRoute
  '/companies': typeof CompaniesIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/employers': typeof AuthenticatedAdminEmployersRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/employer/company': typeof AuthenticatedEmployerCompanyRoute
  '/employer/dashboard': typeof AuthenticatedEmployerDashboardRoute
  '/seeker/applications': typeof AuthenticatedSeekerApplicationsRoute
  '/seeker/coach': typeof AuthenticatedSeekerCoachRoute
  '/seeker/job-matches': typeof AuthenticatedSeekerJobMatchesRoute
  '/seeker/profile': typeof AuthenticatedSeekerProfileRoute
  '/seeker/reports': typeof AuthenticatedSeekerReportsRoute
  '/seeker/resume-analyzer': typeof AuthenticatedSeekerResumeAnalyzerRoute
  '/seeker/saved-jobs': typeof AuthenticatedSeekerSavedJobsRoute
  '/seeker/settings': typeof AuthenticatedSeekerSettingsRoute
  '/seeker/tracker': typeof AuthenticatedSeekerTrackerRoute
  '/employer': typeof AuthenticatedEmployerIndexRoute
  '/employer/jobs/new': typeof AuthenticatedEmployerJobsNewRoute
  '/employer/jobs': typeof AuthenticatedEmployerJobsIndexRoute
  '/employer/jobs/$id/applicants': typeof AuthenticatedEmployerJobsIdApplicantsRoute
  '/employer/jobs/$id/edit': typeof AuthenticatedEmployerJobsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/jobs/$id': typeof JobsIdRoute
  '/reports/$slug': typeof ReportsSlugRoute
  '/companies/': typeof CompaniesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/employers': typeof AuthenticatedAdminEmployersRoute
  '/_authenticated/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/employer/company': typeof AuthenticatedEmployerCompanyRoute
  '/_authenticated/employer/dashboard': typeof AuthenticatedEmployerDashboardRoute
  '/_authenticated/seeker/applications': typeof AuthenticatedSeekerApplicationsRoute
  '/_authenticated/seeker/coach': typeof AuthenticatedSeekerCoachRoute
  '/_authenticated/seeker/job-matches': typeof AuthenticatedSeekerJobMatchesRoute
  '/_authenticated/seeker/profile': typeof AuthenticatedSeekerProfileRoute
  '/_authenticated/seeker/reports': typeof AuthenticatedSeekerReportsRoute
  '/_authenticated/seeker/resume-analyzer': typeof AuthenticatedSeekerResumeAnalyzerRoute
  '/_authenticated/seeker/saved-jobs': typeof AuthenticatedSeekerSavedJobsRoute
  '/_authenticated/seeker/settings': typeof AuthenticatedSeekerSettingsRoute
  '/_authenticated/seeker/tracker': typeof AuthenticatedSeekerTrackerRoute
  '/_authenticated/employer/': typeof AuthenticatedEmployerIndexRoute
  '/_authenticated/employer/jobs/new': typeof AuthenticatedEmployerJobsNewRoute
  '/_authenticated/employer/jobs/': typeof AuthenticatedEmployerJobsIndexRoute
  '/_authenticated/employer/jobs/$id/applicants': typeof AuthenticatedEmployerJobsIdApplicantsRoute
  '/_authenticated/employer/jobs/$id/edit': typeof AuthenticatedEmployerJobsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/dashboard'
    | '/onboarding'
    | '/auth/callback'
    | '/auth/check-email'
    | '/auth/verified'
    | '/companies/$companyId'
    | '/jobs/$id'
    | '/reports/$slug'
    | '/companies/'
    | '/jobs/'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/employers'
    | '/admin/jobs'
    | '/admin/users'
    | '/employer/company'
    | '/employer/dashboard'
    | '/seeker/applications'
    | '/seeker/coach'
    | '/seeker/job-matches'
    | '/seeker/profile'
    | '/seeker/reports'
    | '/seeker/resume-analyzer'
    | '/seeker/saved-jobs'
    | '/seeker/settings'
    | '/seeker/tracker'
    | '/employer/'
    | '/employer/jobs/new'
    | '/employer/jobs/'
    | '/employer/jobs/$id/applicants'
    | '/employer/jobs/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/dashboard'
    | '/onboarding'
    | '/auth/callback'
    | '/auth/check-email'
    | '/auth/verified'
    | '/companies/$companyId'
    | '/jobs/$id'
    | '/reports/$slug'
    | '/companies'
    | '/jobs'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/employers'
    | '/admin/jobs'
    | '/admin/users'
    | '/employer/company'
    | '/employer/dashboard'
    | '/seeker/applications'
    | '/seeker/coach'
    | '/seeker/job-matches'
    | '/seeker/profile'
    | '/seeker/reports'
    | '/seeker/resume-analyzer'
    | '/seeker/saved-jobs'
    | '/seeker/settings'
    | '/seeker/tracker'
    | '/employer'
    | '/employer/jobs/new'
    | '/employer/jobs'
    | '/employer/jobs/$id/applicants'
    | '/employer/jobs/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/auth/callback'
    | '/auth/check-email'
    | '/auth/verified'
    | '/companies/$companyId'
    | '/jobs/$id'
    | '/reports/$slug'
    | '/companies/'
    | '/jobs/'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/employers'
    | '/_authenticated/admin/jobs'
    | '/_authenticated/admin/users'
    | '/_authenticated/employer/company'
    | '/_authenticated/employer/dashboard'
    | '/_authenticated/seeker/applications'
    | '/_authenticated/seeker/coach'
    | '/_authenticated/seeker/job-matches'
    | '/_authenticated/seeker/profile'
    | '/_authenticated/seeker/reports'
    | '/_authenticated/seeker/resume-analyzer'
    | '/_authenticated/seeker/saved-jobs'
    | '/_authenticated/seeker/settings'
    | '/_authenticated/seeker/tracker'
    | '/_authenticated/employer/'
    | '/_authenticated/employer/jobs/new'
    | '/_authenticated/employer/jobs/'
    | '/_authenticated/employer/jobs/$id/applicants'
    | '/_authenticated/employer/jobs/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  CompaniesCompanyIdRoute: typeof CompaniesCompanyIdRoute
  JobsIdRoute: typeof JobsIdRoute
  ReportsSlugRoute: typeof ReportsSlugRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$slug': {
      id: '/reports/$slug'
      path: '/reports/$slug'
      fullPath: '/reports/$slug'
      preLoaderRoute: typeof ReportsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$companyId': {
      id: '/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof CompaniesCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verified': {
      id: '/auth/verified'
      path: '/verified'
      fullPath: '/auth/verified'
      preLoaderRoute: typeof AuthVerifiedRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/check-email': {
      id: '/auth/check-email'
      path: '/check-email'
      fullPath: '/auth/check-email'
      preLoaderRoute: typeof AuthCheckEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/': {
      id: '/_authenticated/employer/'
      path: '/employer'
      fullPath: '/employer/'
      preLoaderRoute: typeof AuthenticatedEmployerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seeker/tracker': {
      id: '/_authenticated/seeker/tracker'
      path: '/seeker/tracker'
      fullPath: '/seeker/tracker'
      preLoaderRoute: typeof AuthenticatedSeekerTrackerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seeker/settings': {
      id: '/_authenticated/seeker/settings'
      path: '/seeker/settings'
      fullPath: '/seeker/settings'
      preLoaderRoute: typeof AuthenticatedSeekerSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seeker/saved-jobs': {
      id: '/_authenticated/seeker/saved-jobs'
      path: '/seeker/saved-jobs'
      fullPath: '/seeker/saved-jobs'
      preLoaderRoute: typeof AuthenticatedSeekerSavedJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seeker/resume-analyzer': {
      id: '/_authenticated/seeker/resume-analyzer'
      path: '/seeker/resume-analyzer'
      fullPath: '/seeker/resume-analyzer'
      preLoaderRoute: typeof AuthenticatedSeekerResumeAnalyzerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seeker/reports': {
      id: '/_authenticated/seeker/reports'
      path: '/seeker/reports'
      fullPath: '/seeker/reports'
      preLoaderRoute: typeof AuthenticatedSeekerReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seeker/profile': {
      id: '/_authenticated/seeker/profile'
      path: '/seeker/profile'
      fullPath: '/seeker/profile'
      preLoaderRoute: typeof AuthenticatedSeekerProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seeker/job-matches': {
      id: '/_authenticated/seeker/job-matches'
      path: '/seeker/job-matches'
      fullPath: '/seeker/job-matches'
      preLoaderRoute: typeof AuthenticatedSeekerJobMatchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seeker/coach': {
      id: '/_authenticated/seeker/coach'
      path: '/seeker/coach'
      fullPath: '/seeker/coach'
      preLoaderRoute: typeof AuthenticatedSeekerCoachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seeker/applications': {
      id: '/_authenticated/seeker/applications'
      path: '/seeker/applications'
      fullPath: '/seeker/applications'
      preLoaderRoute: typeof AuthenticatedSeekerApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/dashboard': {
      id: '/_authenticated/employer/dashboard'
      path: '/employer/dashboard'
      fullPath: '/employer/dashboard'
      preLoaderRoute: typeof AuthenticatedEmployerDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/company': {
      id: '/_authenticated/employer/company'
      path: '/employer/company'
      fullPath: '/employer/company'
      preLoaderRoute: typeof AuthenticatedEmployerCompanyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/jobs': {
      id: '/_authenticated/admin/jobs'
      path: '/admin/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AuthenticatedAdminJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/employers': {
      id: '/_authenticated/admin/employers'
      path: '/admin/employers'
      fullPath: '/admin/employers'
      preLoaderRoute: typeof AuthenticatedAdminEmployersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/jobs/': {
      id: '/_authenticated/employer/jobs/'
      path: '/employer/jobs'
      fullPath: '/employer/jobs/'
      preLoaderRoute: typeof AuthenticatedEmployerJobsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/jobs/new': {
      id: '/_authenticated/employer/jobs/new'
      path: '/employer/jobs/new'
      fullPath: '/employer/jobs/new'
      preLoaderRoute: typeof AuthenticatedEmployerJobsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/jobs/$id/edit': {
      id: '/_authenticated/employer/jobs/$id/edit'
      path: '/employer/jobs/$id/edit'
      fullPath: '/employer/jobs/$id/edit'
      preLoaderRoute: typeof AuthenticatedEmployerJobsIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/jobs/$id/applicants': {
      id: '/_authenticated/employer/jobs/$id/applicants'
      path: '/employer/jobs/$id/applicants'
      fullPath: '/employer/jobs/$id/applicants'
      preLoaderRoute: typeof AuthenticatedEmployerJobsIdApplicantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminEmployersRoute: typeof AuthenticatedAdminEmployersRoute
  AuthenticatedAdminJobsRoute: typeof AuthenticatedAdminJobsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedEmployerCompanyRoute: typeof AuthenticatedEmployerCompanyRoute
  AuthenticatedEmployerDashboardRoute: typeof AuthenticatedEmployerDashboardRoute
  AuthenticatedSeekerApplicationsRoute: typeof AuthenticatedSeekerApplicationsRoute
  AuthenticatedSeekerCoachRoute: typeof AuthenticatedSeekerCoachRoute
  AuthenticatedSeekerJobMatchesRoute: typeof AuthenticatedSeekerJobMatchesRoute
  AuthenticatedSeekerProfileRoute: typeof AuthenticatedSeekerProfileRoute
  AuthenticatedSeekerReportsRoute: typeof AuthenticatedSeekerReportsRoute
  AuthenticatedSeekerResumeAnalyzerRoute: typeof AuthenticatedSeekerResumeAnalyzerRoute
  AuthenticatedSeekerSavedJobsRoute: typeof AuthenticatedSeekerSavedJobsRoute
  AuthenticatedSeekerSettingsRoute: typeof AuthenticatedSeekerSettingsRoute
  AuthenticatedSeekerTrackerRoute: typeof AuthenticatedSeekerTrackerRoute
  AuthenticatedEmployerIndexRoute: typeof AuthenticatedEmployerIndexRoute
  AuthenticatedEmployerJobsNewRoute: typeof AuthenticatedEmployerJobsNewRoute
  AuthenticatedEmployerJobsIndexRoute: typeof AuthenticatedEmployerJobsIndexRoute
  AuthenticatedEmployerJobsIdApplicantsRoute: typeof AuthenticatedEmployerJobsIdApplicantsRoute
  AuthenticatedEmployerJobsIdEditRoute: typeof AuthenticatedEmployerJobsIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminEmployersRoute: AuthenticatedAdminEmployersRoute,
  AuthenticatedAdminJobsRoute: AuthenticatedAdminJobsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedEmployerCompanyRoute: AuthenticatedEmployerCompanyRoute,
  AuthenticatedEmployerDashboardRoute: AuthenticatedEmployerDashboardRoute,
  AuthenticatedSeekerApplicationsRoute: AuthenticatedSeekerApplicationsRoute,
  AuthenticatedSeekerCoachRoute: AuthenticatedSeekerCoachRoute,
  AuthenticatedSeekerJobMatchesRoute: AuthenticatedSeekerJobMatchesRoute,
  AuthenticatedSeekerProfileRoute: AuthenticatedSeekerProfileRoute,
  AuthenticatedSeekerReportsRoute: AuthenticatedSeekerReportsRoute,
  AuthenticatedSeekerResumeAnalyzerRoute:
    AuthenticatedSeekerResumeAnalyzerRoute,
  AuthenticatedSeekerSavedJobsRoute: AuthenticatedSeekerSavedJobsRoute,
  AuthenticatedSeekerSettingsRoute: AuthenticatedSeekerSettingsRoute,
  AuthenticatedSeekerTrackerRoute: AuthenticatedSeekerTrackerRoute,
  AuthenticatedEmployerIndexRoute: AuthenticatedEmployerIndexRoute,
  AuthenticatedEmployerJobsNewRoute: AuthenticatedEmployerJobsNewRoute,
  AuthenticatedEmployerJobsIndexRoute: AuthenticatedEmployerJobsIndexRoute,
  AuthenticatedEmployerJobsIdApplicantsRoute:
    AuthenticatedEmployerJobsIdApplicantsRoute,
  AuthenticatedEmployerJobsIdEditRoute: AuthenticatedEmployerJobsIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthCheckEmailRoute: typeof AuthCheckEmailRoute
  AuthVerifiedRoute: typeof AuthVerifiedRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthCheckEmailRoute: AuthCheckEmailRoute,
  AuthVerifiedRoute: AuthVerifiedRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  CompaniesCompanyIdRoute: CompaniesCompanyIdRoute,
  JobsIdRoute: JobsIdRoute,
  ReportsSlugRoute: ReportsSlugRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
