import React from "react";
import { Page, Text, View, Document, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: "Helvetica",
    backgroundColor: "#ffffff",
  },
  header: {
    marginBottom: 20,
    borderBottom: "2 solid #e2e8f0",
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#0f172a",
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 14,
    color: "#64748b",
  },
  section: {
    marginTop: 20,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#334155",
    marginBottom: 10,
    borderBottom: "1 solid #e2e8f0",
    paddingBottom: 4,
  },
  text: {
    fontSize: 11,
    lineHeight: 1.5,
    color: "#475569",
    marginBottom: 8,
  },
  pillContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 5,
  },
  pill: {
    backgroundColor: "#f1f5f9",
    padding: "4 8",
    borderRadius: 12,
    fontSize: 10,
    color: "#334155",
  },
  suggestionBox: {
    backgroundColor: "#f8fafc",
    padding: 10,
    borderRadius: 4,
    borderLeft: "4 solid #3b82f6",
    marginBottom: 10,
  },
  suggestionTitle: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#1e293b",
    marginBottom: 4,
  },
});

export const ResumePDFDocument = ({ analysis }: { analysis: any }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>ATS Optimization Report</Text>
        <Text style={styles.subtitle}>Generated by JobVerse AI</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Overview</Text>
        <Text style={styles.text}>ATS Score: {analysis.ats_score}/100</Text>
        <Text style={styles.text}>Readiness Score: {analysis.readiness_score}/100</Text>
        <Text style={styles.text}>{analysis.summary}</Text>
      </View>

      {analysis.detected_skills && analysis.detected_skills.length > 0 && (
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Detected Skills</Text>
          <View style={styles.pillContainer}>
            {analysis.detected_skills.map((skill: string, i: number) => (
              <Text key={i} style={styles.pill}>
                {skill}
              </Text>
            ))}
          </View>
        </View>
      )}

      {analysis.missing_keywords && analysis.missing_keywords.length > 0 && (
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Missing Keywords</Text>
          <View style={styles.pillContainer}>
            {analysis.missing_keywords.map((kw: string, i: number) => (
              <Text key={i} style={styles.pill}>
                {kw}
              </Text>
            ))}
          </View>
        </View>
      )}

      {analysis.suggestions && analysis.suggestions.length > 0 && (
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Improvement Suggestions</Text>
          {analysis.suggestions.map((sug: any, i: number) => (
            <View key={i} style={styles.suggestionBox}>
              <Text style={styles.suggestionTitle}>{sug.section}</Text>
              <Text style={styles.text}>{sug.advice}</Text>
            </View>
          ))}
        </View>
      )}
    </Page>
  </Document>
);
